drop table PROBLEM;

create table PROBLEM(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    LONGDESCRIPTION varchar,
    PROBLEMTYPE BigInt,
    CREATEDBY BigInt,
    SHORTDESCRIPTION varchar,

    FOREIGN KEY (PROBLEMTYPE) REFERENCES PROBLEMTYPE(ID),
    FOREIGN KEY (CREATEDBY) REFERENCES USER_T(ID)
);

insert into PROBLEM Values(1, 'Test Problem', 4, 1, 'idkman');

drop table FOLDER;

create table FOLDER(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    LONGDESCRIPTION varchar,
    COURSEID BigInt,
    CREATEDBY BigInt,
    ISPOSED BOOLEAN,
    ENDDATE TimeStamp,
    STARTDATE TimeStamp,
    FOREIGN KEY (COURSEID) REFERENCES COURSE(ID)
);

insert into FOLDER Values(
    1,
    'Homework 1',
    1,
    1,
    false,
    null,
    null
);

drop table PROBLEMPOINTER;

create table PROBLEMPOINTER(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    REFERENCEDPROBLEMID BigInt,
    COURSEID BigInt,
    FOLDERID BigInt,
    ALLOWEDATTEMPTS BigInt,
    MAXGRADE BigInt,

    FOREIGN KEY (REFERENCEDPROBLEMID) REFERENCES PROBLEM(ID),
    FOREIGN KEY (COURSEID) REFERENCES COURSE(ID),
    FOREIGN KEY (FOLDERID) REFERENCES FOLDER(ID)
);

insert into PROBLEMPOINTER Values(1, 1, 1, 1, 10, 10);

-- drop table PROBLEMTOFOLDER;

-- create table PROBLEMTOFOLDER(
--     ID BigInt PRIMARY KEY AUTO_INCREMENT,
--     PROBLEMID BigInt,
--     FOLDERID BigInt,
--     FOREIGN KEY (PROBLEMID) REFERENCES PROBLEMPOINTER(ID),
--     FOREIGN KEY (FOLDERID) REFERENCES FOLDER(ID)
-- );

-- insert into PROBLEMTOFOLDER Values(
--     1,
--     1, 
--     1
-- );
