drop table PROBLEM;

create table PROBLEM(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    LONGDESCRIPTION varchar,
    PROBLEMTYPE BigInt,
    CREATEDBY BigInt,
    SHORTDESCRIPTION varchar,

    FOREIGN KEY (PROBLEMTYPE) REFERENCES PROBLEMTYPE(ID),
    FOREIGN KEY (CREATEDBY) REFERENCES USER_T(ID)
);

drop table PROBLEMLINK;

create table PROBLEMLINK(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    REFERENCEDPROBLEMID BigInt,
    COURSEID BigInt,
    ALLOWEDATTEMPTS BigInt,
    MAXGRADE BigInt,

    FOREIGN KEY (REFERENCEDPROBLEMID) REFERENCES PROBLEM(ID),
    FOREIGN KEY (COURSEID) REFERENCES COURSE(ID)
);

drop table FOLDER;

create table FOLDER(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    LONGDESCRIPTION varchar,
    COURSEID BigInt,
    CREATEDBY BigInt,
    ISPOSED BOOLEAN,
    ENDDATE TimeStamp,
    STARTDATE TimeStamp,
    FOREIGN KEY (COURSEID) REFERENCES COURSE(ID)
);

insert into FOLDER Values(
    1,
    'Homework 1',
    1,
    1,
    false,
    null,
    null
);

insert into FOLDER Values(
    2,
    'Homework 2',
    1,
    1,
    false,
    null,
    null
);

drop table PROBLEMTOFOLDER;

create table PROBLEMTOFOLDER(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    PROBLEMID BigInt,
    FOLDERID BigInt,
    FOREIGN KEY (PROBLEMID) REFERENCES PROBLEMLINK(ID),
    FOREIGN KEY (FOLDERID) REFERENCES FOLDER(ID)
);

insert into PROBLEMTOFOLDER Values(
    1,
    2, 
    1
);
