drop table PROBLEM;

create table PROBLEM(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    LONGDESCRIPTION varchar,
    PROBLEMTYPE BigInt,
    CREATEDBY BigInt,
    SHORTDESCRIPTION varchar,

    FOREIGN KEY (PROBLEMTYPE) REFERENCES PROBLEMTYPE(ID),
    FOREIGN KEY (CREATEDBY) REFERENCES USER_T(ID)
);

drop table FOLDER;

create table FOLDER(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    LONGDESCRIPTION varchar,
    COURSEID BigInt,
    CREATEDBY BigInt,
    ISVISIBLE BOOLEAN,
    ENDDATE TimeStamp,
    STARTDATE TimeStamp,
    FOREIGN KEY (COURSEID) REFERENCES COURSE(ID)
);

drop table PROBLEMPOINTER;

create table PROBLEMPOINTER(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    REFERENCEDPROBLEMID BigInt,
    COURSEID BigInt,
    FOLDERID BigInt,
    ALLOWEDATTEMPTS BigInt,
    MAXGRADE BigInt,

    FOREIGN KEY (REFERENCEDPROBLEMID) REFERENCES PROBLEM(ID),
    FOREIGN KEY (COURSEID) REFERENCES COURSE(ID),
    FOREIGN KEY (FOLDERID) REFERENCES FOLDER(ID)
);

drop table SOLUTIONATTEMPT;

create table SOLUTIONATTEMPT(
    ID BigInt PRIMARY KEY AUTO_INCREMENT,
    PROBLEMPOINTERID BigInt,
    USERID BigInt,
    GRADE Integer,
    DATETIME TimeStamp,

    FOREIGN KEY (PROBLEMPOINTERID) REFERENCES PROBLEMPOINTER(ID),
    FOREIGN KEY (USERID) REFERENCES USER_T(ID)
)
